apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions:
    - key: team
      operator: In
      values:
      - front-end
      - carts
      - catalogue
      - orders
      - payment
      - queue-master
      - shipping
      - user
