apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sock-shop-payment
  labels:
    team: payment
  namespace: sock-shop
spec:
  jobLabel: payment-metrics
  selector:
    matchLabels:
      name: payment
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
