apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sock-shop-user
  labels:
    team: user
  namespace: sock-shop
spec:
  jobLabel: user-metrics
  selector:
    matchLabels:
      name: user
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
